### PR TITLE
Update RequestsKeywords.py

### PR DESCRIPTION
**Pull request by shadeimi**

### CODE REVIEW

**Comment by shadeimi** [comment]
Missing wrong tests on testcase.robot, analyzing the descriptor management against the python 3.5+ functionalities

**Comment by lucagiove** [comment]
But there is no test in this PR in this case an exception is returned that can be passed as data what will happens?
Not sure it's correct this handling.

**Comment by andreagubellini** [comment]
is this pull request still valid / should we keep it and have a review?

**Comment by lucagiove** [comment]
I think is safer let the open raise itself an exception handled by RobotFramework.
Otherwise in case of error a http get/post returns an exception as response.

**Pull request closed without merging**
