### PR TITLE
Deprecates "To Json" in favour of .json() method

### PR DESCRIPTION
**Pull request by andreagubellini**
* Reworked "To Json" test cases
* Removed pretty print test cases 
* Deprecated "To Json" keyword, adding a console warning to use .json method instead

### CODE REVIEW

**Comment by lucagiove** [comment]
I tried to resolve conflicts but couldn't commit to your branch even if the web interface allowed me to.

**Comment by lucagiove** [comment]
I would probably keep the tests until completely removed, deprecated are still somehow supported and should be anyway tested.

**Comment by lucagiove** [comment]
By the way best practice for deprecating keywords:
https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#deprecating-keywords

**Comment by mayribeirofernandes** [comment]
I would like to ask you to rethink not to discontinue the KW "**To JSON**", I usually use it to read JSON from files (string) and turn them into a dictionary to use in KW of the Collections Library, for example, "Dictionary Should Contain Sub Dictionary".

```
${BODY}   Get File   \myFileBody.json
${BODY_REPONSE_EXPECTED}   To Json   ${BODY}
Dictionary Should Contain Sub Dictionary    ${response.json()["data"][0]}    ${BODY_REPONSE_EXPECTED[0]}
```
Or tell me another way to do this, because "Convert To Dictionary" from Builtin don't work for my case.

**Comment by andreagubellini** [comment]
Hi @mayribeirofernandes,

I'm sorry this change has impacts on your workflow.

Perhaps you could try to take a look at `[this](https://github.com/robotframework-thailand/robotframework-jsonlibrary)` library and check if it solves your problem?

**Comment by mayribeirofernandes** [comment]
Thanks for the tip, I'll try! In the last case I will create a customized KW.

**Pull request merged**
